development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d37923f896ddbcdc1d0bbc998b080797@barb.redistogo.com:9777/
  host: barb.redistogo.com
  port: 9777
