development:
  adapter: async

test:
  adapter: async

production:
  adapter: :any_cable
  redis_url: redis://redistogo:d37923f896ddbcdc1d0bbc998b080797@barb.redistogo.com:9777/
  # host: barb.redistogo.com
  # port: 9777

# Run gRPC server:  bundle exec anycable
# Run WebSocket server (e.g. anycable-go):  anycable-go --port 3334

# Run both together locally or on heroku: bundle exec anycable --server-command "anycable-go --port 3334"
